# Generated by Django 3.1.14 on 2023-05-29 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0005_auto_20230529_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='pokemon_id',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.pokemon'),
        ),
    ]
