# Generated by Django 3.1.14 on 2023-06-06 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0018_auto_20230606_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='pokemon_id',
            new_name='pokemon',
        ),
    ]
